// GENERATED by scripts/gen-authz.mjs from the project's OpenAPI contracts
// (specs/design/components/*/openapi.yaml and
// specs/design/components/*/dependencies/*.openapi.yaml).
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after a contract changes. COMMIT this file: the
// per-component image build cannot see the specs tree.
//
// This table is what a screen is gated on. src/authz/screens.ts names the
// operation each screen LOADS; holding that operation's scope is what makes the
// screen reachable. Nothing else in the app decides that.

import type { Scope } from "./roles.gen";

/** What the gateway demands of a caller before it will pass an operation on. */
export type OperationRequirement =
  | { readonly kind: "public" }
  | { readonly kind: "signedIn" }
  | { readonly kind: "scope"; readonly scope: Scope };

/** "<METHOD> <path template>" as the contract spells it, e.g. "GET /me/claims". Sorted. */
export type OperationKey =
  | "DELETE /me/meals/{mealId}"
  | "DELETE /me/workouts/{workoutId}"
  | "GET /health"
  | "GET /me/clients"
  | "GET /me/clients/{traineeId}/history"
  | "GET /me/clients/{traineeId}/summary"
  | "GET /me/clients/{traineeId}/targets"
  | "GET /me/coach-links"
  | "GET /me/feedback"
  | "GET /me/history"
  | "GET /me/meals"
  | "GET /me/summary"
  | "GET /me/targets"
  | "GET /me/workouts"
  | "POST /me/clients/{traineeId}/feedback"
  | "POST /me/coach-links"
  | "POST /me/coach-links/{linkId}/accept"
  | "POST /me/coach-links/{linkId}/revoke"
  | "POST /me/meals"
  | "POST /me/workouts"
  | "PUT /me/meals/{mealId}"
  | "PUT /me/targets"
  | "PUT /me/workouts/{workoutId}";

export const OPERATIONS: Record<OperationKey, OperationRequirement> = {
  "DELETE /me/meals/{mealId}": { kind: "scope", scope: "logs:edit" },
  "DELETE /me/workouts/{workoutId}": { kind: "scope", scope: "logs:edit" },
  "GET /health": { kind: "public" },
  "GET /me/clients": { kind: "scope", scope: "coach-links:list" },
  "GET /me/clients/{traineeId}/history": { kind: "scope", scope: "logs:review" },
  "GET /me/clients/{traineeId}/summary": { kind: "scope", scope: "logs:review" },
  "GET /me/clients/{traineeId}/targets": { kind: "scope", scope: "targets:review" },
  "GET /me/coach-links": { kind: "scope", scope: "coach-links:list" },
  "GET /me/feedback": { kind: "scope", scope: "feedback:read" },
  "GET /me/history": { kind: "scope", scope: "logs:read" },
  "GET /me/meals": { kind: "scope", scope: "logs:read" },
  "GET /me/summary": { kind: "scope", scope: "logs:read" },
  "GET /me/targets": { kind: "scope", scope: "targets:read" },
  "GET /me/workouts": { kind: "scope", scope: "logs:read" },
  "POST /me/clients/{traineeId}/feedback": { kind: "scope", scope: "feedback:create" },
  "POST /me/coach-links": { kind: "scope", scope: "coach-links:invite" },
  "POST /me/coach-links/{linkId}/accept": { kind: "scope", scope: "coach-links:accept" },
  "POST /me/coach-links/{linkId}/revoke": { kind: "scope", scope: "coach-links:revoke" },
  "POST /me/meals": { kind: "scope", scope: "logs:log" },
  "POST /me/workouts": { kind: "scope", scope: "logs:log" },
  "PUT /me/meals/{mealId}": { kind: "scope", scope: "logs:edit" },
  "PUT /me/targets": { kind: "scope", scope: "targets:set" },
  "PUT /me/workouts/{workoutId}": { kind: "scope", scope: "logs:edit" },
};

export function isOperationKey(value: string): value is OperationKey {
  return Object.prototype.hasOwnProperty.call(OPERATIONS, value);
}
