// Generated by the Ballerina OpenAPI tool from openapi.yaml, then filled in
// by hand: every resource body, the interceptor wiring, and the listener's
// bind address. The generated types below (Target, MealLog, CoachLink, ...)
// and the resource signatures are left as `bal openapi` produced them.

import ballerina/http;
import ballerinax/postgresql;

listener http:Listener ep0 = new (9090);

service http:InterceptableService / on ep0 {
    public function createInterceptors() returns AssertionInterceptor => new;

    # Liveness check
    #
    # + return - Service is healthy
    resource function get health() returns http:Ok {
        return <http:Ok>{body: {status: "ok"}};
    }

    // ---- Trainee: targets --------------------------------------------

    # The caller's current targets
    resource function get me/targets(http:RequestContext ctx) returns Target|ErrorNotFound|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized(caller);
        }
        postgresql:Client dbClient = check db();
        Target? target = check fetchTarget(dbClient, caller.userId);
        if target is () {
            return notFound("no targets set yet");
        }
        return target;
    }

    # Create or update the caller's targets
    resource function put me/targets(http:RequestContext ctx, @http:Payload me_targets_body payload) returns Target|ErrorBadRequest|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized(caller);
        }
        string? validationError = validateMacros(payload.caloriesKcal, payload.proteinG, payload.carbsG, payload.fatG);
        if validationError is string {
            return badRequest(validationError);
        }
        postgresql:Client dbClient = check db();
        Target target = check upsertTarget(dbClient, caller.userId, payload.caloriesKcal, payload.proteinG, payload.carbsG, payload.fatG);
        return target;
    }

    // ---- Trainee: meals -------------------------------------------------

    # The caller's own meal logs
    resource function get me/meals(http:RequestContext ctx, string? date, int 'limit = 20, int offset = 0) returns inline_response_200|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized(caller);
        }
        postgresql:Client dbClient = check db();
        MealPage page = check listMeals(dbClient, caller.userId, date, 'limit, offset);
        return {
            count: page.total,
            next: paginationNext("/me/meals", 'limit, offset, page.total),
            previous: paginationPrevious("/me/meals", 'limit, offset),
            data: page.items
        };
    }

    # Create a meal log entry
    resource function post me/meals(http:RequestContext ctx, @http:Payload MealLogInput payload) returns MealLog|ErrorBadRequest|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized(caller);
        }
        string? validationError = validateMealInput(payload);
        if validationError is string {
            return badRequest(validationError);
        }
        postgresql:Client dbClient = check db();
        MealLog meal = check createMeal(dbClient, caller.userId, payload);
        return meal;
    }

    # Update the caller's own meal log entry
    resource function put me/meals/[string mealId](http:RequestContext ctx, @http:Payload MealLogInput payload) returns MealLog|ErrorNotFound|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized(caller);
        }
        postgresql:Client dbClient = check db();
        MealLog? meal = check updateMeal(dbClient, caller.userId, mealId, payload);
        if meal is () {
            return notFound("no such meal log");
        }
        return meal;
    }

    # Delete the caller's own meal log entry
    resource function delete me/meals/[string mealId](http:RequestContext ctx) returns http:NoContent|ErrorNotFound|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized(caller);
        }
        postgresql:Client dbClient = check db();
        boolean deleted = check deleteMeal(dbClient, caller.userId, mealId);
        if !deleted {
            return notFound("no such meal log");
        }
        return http:NO_CONTENT;
    }

    // ---- Trainee: workouts ------------------------------------------

    # The caller's own workout logs
    resource function get me/workouts(http:RequestContext ctx, string? date, int 'limit = 20, int offset = 0) returns inline_response_200_1|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized(caller);
        }
        postgresql:Client dbClient = check db();
        WorkoutPage page = check listWorkouts(dbClient, caller.userId, date, 'limit, offset);
        return {
            count: page.total,
            next: paginationNext("/me/workouts", 'limit, offset, page.total),
            previous: paginationPrevious("/me/workouts", 'limit, offset),
            data: page.items
        };
    }

    # Create a workout log entry
    resource function post me/workouts(http:RequestContext ctx, @http:Payload WorkoutLogInput payload) returns WorkoutLog|ErrorBadRequest|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized(caller);
        }
        string? validationError = validateWorkoutInput(payload);
        if validationError is string {
            return badRequest(validationError);
        }
        postgresql:Client dbClient = check db();
        WorkoutLog workout = check createWorkout(dbClient, caller.userId, payload);
        return workout;
    }

    # Update the caller's own workout log entry
    resource function put me/workouts/[string workoutId](http:RequestContext ctx, @http:Payload WorkoutLogInput payload) returns WorkoutLog|ErrorNotFound|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized(caller);
        }
        postgresql:Client dbClient = check db();
        WorkoutLog? workout = check updateWorkout(dbClient, caller.userId, workoutId, payload);
        if workout is () {
            return notFound("no such workout log");
        }
        return workout;
    }

    # Delete the caller's own workout log entry
    resource function delete me/workouts/[string workoutId](http:RequestContext ctx) returns http:NoContent|ErrorNotFound|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized(caller);
        }
        postgresql:Client dbClient = check db();
        boolean deleted = check deleteWorkout(dbClient, caller.userId, workoutId);
        if !deleted {
            return notFound("no such workout log");
        }
        return http:NO_CONTENT;
    }

    // ---- Trainee: summary & history -----------------------------------

    # The caller's daily macro summary against targets
    resource function get me/summary(http:RequestContext ctx, string? date) returns DailySummary|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized(caller);
        }
        string targetDate = date ?: todayDate();
        postgresql:Client dbClient = check db();
        DailySummary summary = check computeDailySummary(dbClient, caller.userId, targetDate);
        return summary;
    }

    # The caller's trailing 7-day history
    resource function get me/history(http:RequestContext ctx) returns WeeklyHistory|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized(caller);
        }
        postgresql:Client dbClient = check db();
        WeeklyHistory history = check weeklyHistory(dbClient, caller.userId);
        return history;
    }

    // ---- Coach links -----------------------------------------------------

    # The caller's own coach invites/links, sent or received
    resource function get me/coach\-links(http:RequestContext ctx, "pending"|"accepted"|"revoked"? status, int 'limit = 20, int offset = 0) returns inline_response_200_2|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized(caller);
        }
        postgresql:Client dbClient = check db();
        CoachLinkPage page = check listMyCoachLinks(dbClient, caller, status, 'limit, offset);
        return {
            count: page.total,
            next: paginationNext("/me/coach-links", 'limit, offset, page.total),
            previous: paginationPrevious("/me/coach-links", 'limit, offset),
            data: page.items
        };
    }

    # Invite a coach by email or username
    resource function post me/coach\-links(http:RequestContext ctx, @http:Payload CoachLinkInput payload) returns CoachLink|ErrorBadRequest|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized(caller);
        }
        string? validationError = validateCoachLinkInput(payload);
        if validationError is string {
            return badRequest(validationError);
        }
        postgresql:Client dbClient = check db();
        CoachLink|string outcome = check createCoachLinkInvite(dbClient, caller.userId, payload.coachEmailOrUsername);
        if outcome is string {
            return badRequest(outcome);
        }
        return outcome;
    }

    # Accept a pending invite addressed to the caller
    resource function post me/coach\-links/[string linkId]/accept(http:RequestContext ctx) returns CoachLinkOk|ErrorNotFound|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized(caller);
        }
        postgresql:Client dbClient = check db();
        CoachLink? link = check acceptCoachLink(dbClient, linkId, caller);
        if link is () {
            return notFound("no such pending invite");
        }
        return <CoachLinkOk>{body: link};
    }

    # Revoke a coach link owned by the caller as trainee
    resource function post me/coach\-links/[string linkId]/revoke(http:RequestContext ctx) returns CoachLinkOk|ErrorNotFound|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized(caller);
        }
        postgresql:Client dbClient = check db();
        CoachLink? link = check revokeCoachLink(dbClient, linkId, caller.userId);
        if link is () {
            return notFound("no such link");
        }
        return <CoachLinkOk>{body: link};
    }

    // ---- Feedback (trainee's own) ---------------------------------------

    # The caller's own received feedback
    resource function get me/feedback(http:RequestContext ctx, int 'limit = 20, int offset = 0) returns inline_response_200_3|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized(caller);
        }
        postgresql:Client dbClient = check db();
        FeedbackPage page = check listMyFeedback(dbClient, caller.userId, 'limit, offset);
        return {
            count: page.total,
            next: paginationNext("/me/feedback", 'limit, offset, page.total),
            previous: paginationPrevious("/me/feedback", 'limit, offset),
            data: page.items
        };
    }

    // ---- Coach: clients ---------------------------------------------------

    # The coach's accepted trainee links
    resource function get me/clients(http:RequestContext ctx, int 'limit = 20, int offset = 0) returns inline_response_200_2|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized(caller);
        }
        postgresql:Client dbClient = check db();
        CoachLinkPage page = check listMyClients(dbClient, caller.userId, 'limit, offset);
        return {
            count: page.total,
            next: paginationNext("/me/clients", 'limit, offset, page.total),
            previous: paginationPrevious("/me/clients", 'limit, offset),
            data: page.items
        };
    }

    # A linked client's targets
    resource function get me/clients/[string traineeId]/targets(http:RequestContext ctx) returns Target|ErrorNotFound|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized(caller);
        }
        postgresql:Client dbClient = check db();
        CoachLink? link = check findAcceptedLink(dbClient, caller.userId, traineeId);
        if link is () {
            return notFound("no accepted link with this trainee");
        }
        Target? target = check fetchTarget(dbClient, traineeId);
        return target ?: emptyTarget(todayDate());
    }

    # A linked client's daily macro summary against targets
    resource function get me/clients/[string traineeId]/summary(http:RequestContext ctx, string? date) returns DailySummary|ErrorNotFound|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized(caller);
        }
        postgresql:Client dbClient = check db();
        CoachLink? link = check findAcceptedLink(dbClient, caller.userId, traineeId);
        if link is () {
            return notFound("no accepted link with this trainee");
        }
        string targetDate = date ?: todayDate();
        DailySummary summary = check computeDailySummary(dbClient, traineeId, targetDate);
        return summary;
    }

    # A linked client's trailing 7-day history
    resource function get me/clients/[string traineeId]/history(http:RequestContext ctx) returns WeeklyHistory|ErrorNotFound|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized(caller);
        }
        postgresql:Client dbClient = check db();
        CoachLink? link = check findAcceptedLink(dbClient, caller.userId, traineeId);
        if link is () {
            return notFound("no accepted link with this trainee");
        }
        WeeklyHistory history = check weeklyHistory(dbClient, traineeId);
        return history;
    }

    # Leave feedback for a linked client
    resource function post me/clients/[string traineeId]/feedback(http:RequestContext ctx, @http:Payload FeedbackInput payload) returns Feedback|ErrorNotFound|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return toUnauthorized(caller);
        }
        postgresql:Client dbClient = check db();
        CoachLink? link = check findAcceptedLink(dbClient, caller.userId, traineeId);
        if link is () {
            return notFound("no accepted link with this trainee");
        }
        Feedback feedback = check createFeedback(dbClient, link.id, caller.userId, payload);
        return feedback;
    }
}

public type CoachLink record {
    string id;
    string traineeId?;
    string traineeDisplayName?;
    string coachEmailOrUsername?;
    "pending"|"accepted"|"revoked" status;
    string invitedAt;
    string? respondedAt?;
};

public type MealLog record {
    string id;
    string loggedDate;
    string name;
    int caloriesKcal;
    int proteinG;
    int carbsG;
    int fatG;
};

public type ExerciseEntry record {
    string exerciseName;
    int sets;
    int reps;
    decimal weightKg;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type MealLogInput record {
    string loggedDate;
    string name;
    int caloriesKcal;
    int proteinG;
    int carbsG;
    int fatG;
};

public type CoachLinkInput record {
    string coachEmailOrUsername;
};

public type DailySummary record {
    string date;
    Target target;
    DailySummary_totals totals;
};

public type DailySummary_totals record {
    int caloriesKcal?;
    int proteinG?;
    int carbsG?;
    int fatG?;
};

public type Target record {
    string id;
    int caloriesKcal;
    int proteinG;
    int carbsG;
    int fatG;
    string effectiveFrom;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type FeedbackInput record {
    string forDate;
    string message;
};

public type WorkoutLog record {
    string id;
    string loggedDate;
    "strength"|"cardio" 'type;
    int? cardioDurationMin?;
    ExerciseEntry[] exercises?;
};

public type Feedback record {
    string id;
    string coachLinkId?;
    string forDate;
    string message;
    string createdAt;
};

public type inline_response_200_1 record {
    int count;
    string? next?;
    string? previous?;
    WorkoutLog[] data;
};

public type CoachLinkOk record {|
    *http:Ok;
    CoachLink body;
|};

public type me_targets_body record {
    int caloriesKcal;
    int proteinG;
    int carbsG;
    int fatG;
};

public type inline_response_200 record {
    int count;
    string? next?;
    string? previous?;
    MealLog[] data;
};

public type inline_response_200_2 record {
    int count;
    string? next?;
    string? previous?;
    CoachLink[] data;
};

public type WorkoutLogInput record {
    string loggedDate;
    "strength"|"cardio" 'type;
    int? cardioDurationMin?;
    ExerciseEntry[] exercises?;
};

public type inline_response_200_3 record {
    int count;
    string? next?;
    string? previous?;
    Feedback[] data;
};

public type WeeklyHistory record {
    DailySummary[] days;
};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
